### ISSUE TITLE
installation test error

### ISSUE THREAD

**Issue by logosAllen** [idiap/facereclib#13]
Hello,

I could not pass ./bin/nosetests
it showed:
```
test01_gabor_jet (facereclib.tests.test_tools.ToolTest) ... ok
test02_lgbphs (facereclib.tests.test_tools.ToolTest) ... ok
test03_pca (facereclib.tests.test_tools.ToolTest) ... ok
test04_lda (facereclib.tests.test_tools.ToolTest) ... ok
test05_bic (facereclib.tests.test_tools.ToolTest) ... ok
test06_gmm (facereclib.tests.test_tools.ToolTest) ... ERROR
test06a_gmm_regular (facereclib.tests.test_tools.ToolTest) ... ERROR
test07_isv (facereclib.tests.test_tools.ToolTest) ... ERROR
test08_jfa (facereclib.tests.test_tools.ToolTest) ... ERROR
test09_plda (facereclib.tests.test_tools.ToolTest) ... ok
test10_ivector (facereclib.tests.test_tools.ToolTest) ... ERROR

======================================================================
ERROR: test06_gmm (facereclib.tests.test_tools.ToolTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/FacerecLib/FacerecLib/facereclib-2.1.2/facereclib/tests/test_tools.py", line 347, in test06_gmm
    tool.train_projector(facereclib.utils.tests.random_training_set(feature.shape, count=5, minimum=-5., maximum=5.), t)
  File "/home/FacerecLib/FacerecLib/facereclib-2.1.2/facereclib/tools/UBMGMM.py", line 190, in train_projector
    self._train_projector_using_array(array)
  File "/home/FacerecLib/FacerecLib/facereclib-2.1.2/facereclib/tools/UBMGMM.py", line 160, in _train_projector_using_array
    self.__multiply_vectors_by_factors__(means, std_array)
  File "/home/FacerecLib/FacerecLib/facereclib-2.1.2/facereclib/tools/UBMGMM.py", line 121, in __multiply_vectors_by_factors__
    matrix[i, j] *= vector[j]
ValueError: assignment destination is read-only

======================================================================
ERROR: test06a_gmm_regular (facereclib.tests.test_tools.ToolTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/FacerecLib/FacerecLib/facereclib-2.1.2/facereclib/tests/test_tools.py", line 398, in test06a_gmm_regular
    tool.train_enroller(facereclib.utils.tests.random_training_set(feature.shape, count=5, minimum=-5., maximum=5.), t)
  File "/home/FacerecLib/FacerecLib/facereclib-2.1.2/facereclib/tools/UBMGMM.py", line 292, in train_enroller
    return self.train_projector(train_features, enroller_file)
  File "/home/FacerecLib/FacerecLib/facereclib-2.1.2/facereclib/tools/UBMGMM.py", line 190, in train_projector
    self._train_projector_using_array(array)
  File "/home/FacerecLib/FacerecLib/facereclib-2.1.2/facereclib/tools/UBMGMM.py", line 160, in _train_projector_using_array
    self.__multiply_vectors_by_factors__(means, std_array)
  File "/home/FacerecLib/FacerecLib/facereclib-2.1.2/facereclib/tools/UBMGMM.py", line 121, in __multiply_vectors_by_factors__
    matrix[i, j] *= vector[j]
ValueError: assignment destination is read-only

======================================================================
ERROR: test07_isv (facereclib.tests.test_tools.ToolTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/FacerecLib/FacerecLib/facereclib-2.1.2/facereclib/tests/test_tools.py", line 438, in test07_isv
    tool.train_projector(facereclib.utils.tests.random_training_set_by_id(feature.shape, count=5, minimum=-5., maximum=5.), t)
  File "/home/FacerecLib/FacerecLib/facereclib-2.1.2/facereclib/tools/ISV.py", line 74, in train_projector
    UBMGMM._train_projector_using_array(self, data1)
  File "/home/FacerecLib/FacerecLib/facereclib-2.1.2/facereclib/tools/UBMGMM.py", line 160, in _train_projector_using_array
    self.__multiply_vectors_by_factors__(means, std_array)
  File "/home/FacerecLib/FacerecLib/facereclib-2.1.2/facereclib/tools/UBMGMM.py", line 121, in __multiply_vectors_by_factors__
    matrix[i, j] *= vector[j]
ValueError: assignment destination is read-only

======================================================================
ERROR: test08_jfa (facereclib.tests.test_tools.ToolTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/FacerecLib/FacerecLib/facereclib-2.1.2/facereclib/tests/test_tools.py", line 516, in test08_jfa
    tool.train_projector(facereclib.utils.tests.random_training_set(feature.shape, count=5, minimum=-5., maximum=5.), t)
  File "/home/FacerecLib/FacerecLib/facereclib-2.1.2/facereclib/tools/UBMGMM.py", line 190, in train_projector
    self._train_projector_using_array(array)
  File "/home/FacerecLib/FacerecLib/facereclib-2.1.2/facereclib/tools/UBMGMM.py", line 160, in _train_projector_using_array
    self.__multiply_vectors_by_factors__(means, std_array)
  File "/home/FacerecLib/FacerecLib/facereclib-2.1.2/facereclib/tools/UBMGMM.py", line 121, in __multiply_vectors_by_factors__
    matrix[i, j] *= vector[j]
ValueError: assignment destination is read-only

======================================================================
ERROR: test10_ivector (facereclib.tests.test_tools.ToolTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/FacerecLib/FacerecLib/facereclib-2.1.2/facereclib/tests/test_tools.py", line 648, in test10_ivector
    tool.train_projector(facereclib.utils.tests.random_training_set(feature.shape, count=5, minimum=-5., maximum=5.), t)
  File "/home/FacerecLib/FacerecLib/facereclib-2.1.2/facereclib/tools/IVector.py", line 90, in train_projector
    UBMGMM._train_projector_using_array(self, data)
  File "/home/FacerecLib/FacerecLib/facereclib-2.1.2/facereclib/tools/UBMGMM.py", line 160, in _train_projector_using_array
    self.__multiply_vectors_by_factors__(means, std_array)
  File "/home/FacerecLib/FacerecLib/facereclib-2.1.2/facereclib/tools/UBMGMM.py", line 121, in __multiply_vectors_by_factors__
    matrix[i, j] *= vector[j]
ValueError: assignment destination is read-only

======================================================================
FAIL: test11_landmarkdetect (facereclib.tests.test_preprocessing.PreprocessingTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/FacerecLib/FacerecLib/facereclib-2.1.2/facereclib/tests/test_preprocessing.py", line 181, in test11_landmarkdetect
    self.execute(preprocessor, data, annotation, 'landmark.hdf5', 1e-3)
  File "/home/FacerecLib/FacerecLib/facereclib-2.1.2/facereclib/tests/test_preprocessing.py", line 55, in execute
    self.assertTrue((numpy.abs(facereclib.utils.load(self.reference_dir(reference)) - preprocessed) < max_diff).all())
AssertionError: False is not true

----------------------------------------------------------------------
Ran 57 tests in 130.134s

FAILED (SKIP=3, errors=5, failures=1)
```
Here is my environment and Process.

- OS: ubuntu 14.04 docker image
- facereclib version: 2.1.2
- Process: 

1. install Bob dependency
```
sudo apt-get install software-properties-common python-software-properties
sudo add-apt-repository ppa:biometrics/bob
sudo apt-get update
sudo apt-get install wget git-core pkg-config cmake python-dev python-support liblapack-dev libatlas-base-dev libblitz1-dev libavformat-dev libavcodec-dev libswscale-dev libboost-all-dev libmatio-dev libjpeg8-dev libnetpbm10-dev libpng12-dev libtiff4-dev libgif-dev libhdf5-serial-dev libfftw3-dev texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended libsvm-dev libvl-dev dvipng python-numpy python-scipy dvipng libopencv-dev gcc g++ make python-argparse python-matplotlib python-tornado python-sqlalchemy python-sphinx python-nose python-setuptools python-imaging ipython python-ipdb python3-matplotlib python3-tornado python3-sqlalchemy python3-sphinx python3-nose python3-setuptools python3-imaging ipython3 python3-ipdb python3-dev python3-numpy python3-scipy
```

2. install Bob follow this page(success)
https://github.com/idiap/bob/wiki/Installation

3. set-up the FacerecLib
```
$ cd /home/allen/FacerecLib/FacerecLib/facereclib-2.1.2
$ python bootstrap-buildout.py
$ ./bin/buildout

```

4. test(failed)
`$ ./bin/nosetests`

Thanks!!

Allen

**Comment by anjos** [comment]
Hello,

This package has been superseeded by `bob.bio.face` (https://pypi.python.org/pypi/bob.bio.face).

Could you please try to install that one instead and let us know if you have problems?

Also, please use our mailing list for questions like this:

https://groups.google.com/forum/?fromgroups#!forum/bob-devel
